---
title: Christmas
author: Elizee
date: Winter 2025
output:
  ioslides_presentation:
    incremental: true
    widescreen: true
---

<!-- Global -->
<style>
.reveal .slides {
    color: #213d25ff;
  background-color: rgba(158, 201, 163, 1);
}
</style>

## How many elves should it take to make all the presents for the uk.

- Assumptions 
  - They work from 1 January to the 24 of December 
  - 9 to 5 
  - 5 days a week
  - Each child under 16 gets 3 presents.
  - You make assumptions for everything else based on research
    - E.g. how long each present takes on average 



## Example Solution

- Research and estimate hours needed per present (on average)
    - e.g. 2 hrs (elves are magic fight me) 

- Research average working days in a year
    - 260

- calculate - Elf present output
    -  Elf present output = days they can work * 8 hours / hours needed per present (on average)
    -  Elf present output = (260 * 8) / 2
    -  Elf present output = 1040



## Example Solution pt 2

- Research/Calculate quantity of population under 16
    - Poputaion of uk is 69,729,988 (https://www.worldometers.info/world-population/uk-population/)
    - 19.5 % under 16 (https://lginform.local.gov.uk/reports/lgastandard?mod-metric=3288&mod-area=E92000001&mod-group=AllRegions_England&mod-type=namedComparisonGroup)
    - ∴ quantity of children under 16 = 69,729,988 * 0.195
    - quantity of children under 16 = 13597347.7
    - 13597348


## Example Solution pt 3

- Calculate - presents needed
    - presents needed = children under 16 * 3 presents 
    - presents needed = 13597348 * 3
    - presents needed = 40792044

- Calculate - elves required 
    - elves required = presents needed / elf present output 
    - elves required = 40792044 / 1040
    - elves required = 39223.1192
    - elves required = 39224


# Your Task

## Winter Gift Bringers

- There are many winter gift-bringers around the world.
- Assume that each person who "believes" requires a visit, and a gift brought, by one gift-bringer.
  - Each gift-bringer's survival depends on people believing in them. 
    - Belief increases if the gift bringer pays a visit, and increases more (how much?) if the gift-bringer aligns with the individuals religious / cultural views. 
    - Belief decreases with no visit, and decreases more (how much?) if an expected visit is missed. 
  - If a second gift-bringer arrives, the individual will turn them away, and won't believe in them.
  - If a gift-bringer strongly opposes a person's cultural or religious view, then the person may be offended and belief decreases. 

## Winter Gift Bringers

- Choose at least three and work out how they can divide up gift-bringing duties such that
  - Each person receives a visit between 00:00 and 07:00 on the morning of their respective celebration day*. 
  - All gift-bringers survive Christmas night. 

## A few examples of gift bringers

- "Old man": (Santa Claus, St Nick, Father Christmas, St Basil, Grandfather Frost)
- Christchild (Jesus, Three Kings)
- Crampus (punishes naughty children with birch rods).
- Any others you'd like to include. 
- Note that different gift-bringers visit on different days (6 Dec, 25 Dec, 1 Jan, 6 Jan).

## You may want to think about:

- Travel time / means of travel / cost (fuel, reindeer food, etc)
- Procurement / manufacture of gifts.
- "Belief utility function", who to visit to maximise belief and ensure survival. 
- Should gift-bringers team up or compete?
